import { existsSync, readFileSync, writeFileSync } from "node:fs"
import { createApi } from "./api.ts"
import { createSpacesKey, createBucket } from "./spaces.ts"
import { generateSecret } from "./secret.ts"
import { ensureSshKey } from "./sshkey.ts"
import { createDroplet, findDroplet, ipFor, waitForActive } from "./droplet.ts"
import { generateCloudInit } from "./cloudinit.ts"

const arg = (key: string, fallback?: string) => {
  const prefix = `--${key}=`
  const found = process.argv.find(a => a.startsWith(prefix))
  if (found) return found.slice(prefix.length)
  const envKey = key.toUpperCase().replace(/-/g, "_")
  return process.env[envKey] ?? fallback
}

const die = (msg: string): never => {
  console.error(`✗ ${msg}`)
  process.exit(1)
}

const parseEnv = (text: string): Record<string, string> => {
  const out: Record<string, string> = {}
  for (const line of text.split("\n")) {
    const m = line.match(/^([A-Z_][A-Z0-9_]*)=(.*)$/)
    if (m) out[m[1]!] = m[2]!
  }
  return out
}

const main = async () => {
  const token = process.env.DIGITALOCEAN_TOKEN
  if (!token) die("DIGITALOCEAN_TOKEN is required (export DIGITALOCEAN_TOKEN=...)")

  const githubRepo = arg("github") ?? process.env.GITHUB_REPO
  if (!githubRepo) die("--github=user/repo is required (or set GITHUB_REPO)")

  const config = {
    appName: arg("app-name", "stohr")!,
    region: arg("region", "nyc3")!,
    size: arg("size", "s-1vcpu-1gb")!,
    image: arg("image", "ubuntu-22-04-x64")!,
    branch: arg("branch", "main")!,
    domain: arg("domain") ?? null,
    bucket: arg("bucket", `stohr-files-${Math.random().toString(36).slice(2, 8)}`)!,
    sshPubKey: arg("ssh-pub-key"),
    githubToken: arg("github-token"),
  }

  console.log(`▸ deploying "${config.appName}"`)
  console.log(`  region : ${config.region}`)
  console.log(`  size   : ${config.size}  (about $6/mo for s-1vcpu-1gb)`)
  console.log(`  image  : ${config.image}`)
  console.log(`  github : ${githubRepo}@${config.branch}`)
  console.log(`  bucket : ${config.bucket}`)
  console.log(`  domain : ${config.domain ?? "(none — Caddy serves on :80 over the IP)"}`)
  console.log("")

  const api = createApi(token!)
  await api.request("GET", "/account")

  const existing = await findDroplet(api, config.appName)
  if (existing) {
    die(`droplet "${config.appName}" already exists (id=${existing.id}). Pass --app-name=<other> or delete it.`)
  }

  const credsPath = "scripts/deploy/.env.local"
  const saved = existsSync(credsPath) ? parseEnv(readFileSync(credsPath, "utf8")) : {}
  const secret = saved.SECRET ?? generateSecret()
  const postgresPassword = saved.POSTGRES_PASSWORD ?? generateSecret(16)
  let s3AccessKey = process.env.S3_ACCESS_KEY ?? saved.S3_ACCESS_KEY
  let s3SecretKey = process.env.S3_SECRET_KEY ?? saved.S3_SECRET_KEY

  if (!s3AccessKey || !s3SecretKey) {
    console.log("▸ creating Spaces access key")
    try {
      const key = await createSpacesKey(api, `${config.appName}-key`, config.bucket)
      s3AccessKey = key.access_key
      s3SecretKey = key.secret_key
    } catch (e: any) {
      die(
        `Could not auto-create Spaces key (${e.message}).\n  ` +
        `Create one in Spaces → Access Keys, then re-run with:\n` +
        `    S3_ACCESS_KEY=... S3_SECRET_KEY=... bun scripts/deploy/index.ts --github=${githubRepo}`,
      )
    }
  }

  console.log(`▸ creating bucket ${config.bucket}`)
  const { created } = await createBucket(config.region, s3AccessKey!, s3SecretKey!, config.bucket)
  console.log(`  ${created ? "created" : "already existed"}`)

  console.log("▸ ensuring SSH key on DO")
  const sshKey = await ensureSshKey(api, config.sshPubKey)
  console.log(`  using ${sshKey.path} (id=${sshKey.id})`)

  writeFileSync(credsPath, [
    "# Generated by scripts/deploy — do not commit.",
    `SECRET=${secret}`,
    `POSTGRES_PASSWORD=${postgresPassword}`,
    `S3_ACCESS_KEY=${s3AccessKey}`,
    `S3_SECRET_KEY=${s3SecretKey}`,
    `S3_BUCKET=${config.bucket}`,
    `S3_REGION=${config.region}`,
    `S3_ENDPOINT=https://${config.region}.digitaloceanspaces.com`,
  ].join("\n") + "\n", { mode: 0o600 })
  console.log(`  credentials saved to ${credsPath} (mode 600)`)

  const userData = generateCloudInit({
    githubRepo: githubRepo!,
    branch: config.branch,
    githubToken: config.githubToken,
    postgresPassword,
    secret,
    s3Endpoint: `https://${config.region}.digitaloceanspaces.com`,
    s3Bucket: config.bucket,
    s3Region: config.region,
    s3AccessKey: s3AccessKey!,
    s3SecretKey: s3SecretKey!,
    domain: config.domain,
  })

  console.log("▸ creating droplet")
  const droplet = await createDroplet(api, {
    name: config.appName,
    region: config.region,
    size: config.size,
    image: config.image,
    sshKeyIds: [sshKey.id],
    userData,
  })
  console.log(`  id=${droplet.id}, waiting for active…`)
  const ready = await waitForActive(api, droplet.id)
  const ip = ipFor(ready)

  console.log("")
  console.log("✓ droplet up")
  console.log(`  ip: ${ip}`)
  console.log("")
  if (config.domain) {
    console.log(`  next:`)
    console.log(`    1. point ${config.domain} A record → ${ip}`)
    console.log(`    2. wait ~5–10 min for cloud-init: docker install, repo clone, image build, services up`)
    console.log(`    3. visit https://${config.domain}`)
  } else {
    console.log(`  next:`)
    console.log(`    1. wait ~5–10 min for cloud-init: docker install, repo clone, image build, services up`)
    console.log(`    2. visit http://${ip}`)
  }
  console.log("")
  console.log(`  follow progress:  ssh root@${ip} 'tail -f /var/log/stohr-bootstrap.log'`)
}

main().catch(err => {
  console.error(`✗ ${err.message}`)
  process.exit(1)
})
