name: stohrshot
description: Stohr screenshot menu-bar app
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  tray_manager: ^0.5.1
  hotkey_manager: ^0.2.3
  window_manager: ^0.5.1
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  http: ^1.1.0
  crypto: ^3.0.6
  stohr:
    path: ../../sdks/dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
